services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - meetu_net
  nginx:
    image: nginx:alpine
    networks:
      - meetu_net
    restart: always
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
networks:
  meetu_net:
    driver: bridge
