services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    command: npm run start
    environment:
      - NEXT_DISABLE_FILE_WATCHER=true
    ports:
      - "3000:3000"
    networks:
      - meetu_net

networks:
  meetu_net:
    driver: bridge
